name: Build and release
on:
  push:
    branches:
      - '**'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  build:
    name: bidrag-tilgangskontroll, build and release...
    runs-on: self-hosted

    steps:
      - run: env
      - run: sudo rm -rf *
      - uses: actions/checkout@v2
      - uses: navikt/bidrag-maven/verify-dependencies@v1
        with:
          maven_image: maven:3.6.3-jdk-13
      - name: run maven batch install...
        run: docker run --rm -v $PWD:/usr/src/mymaven -v ~/.m2:/root/.m2 -w /usr/src/mymaven maven:3.6.3-jdk-13 mvn install -B -e

  release:
    name: release artifact to Maven repo
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: self-hosted

    steps:
      - run: env
      - uses: navikt/bidrag-release/verify-auto-release@v3
        id: verify
        if: github.ref == 'refs/heads/master'
        with:
          changelog_file: endringer.logg
          release_version: ${{ steps.prepare_release.outputs.release_version }}

      - name: Collect versions...
        id: prepare_release
        if: ${{ steps.verify.outputs.is_release_candidate  == 'true' &&  github.ref == 'refs/heads/master' }}
        run: |
          SNAPSHOT_VERSION_LINE=$(grep version pom.xml | grep SNAPSHOT)
          SNAPSHOT_VERSION=$(echo "$SNAPSHOT_VERSION_LINE" | sed 's/version//g' | sed 's/  //' | sed 's;[</>];;g' | xargs)
          RELEASE_VERSION=$(echo "$SNAPSHOT_VERSION" | sed 's/version//g' | sed 's/  //' | sed 's/-SNAPSHOT//' | sed 's;[</>];;g' | xargs)
          echo ::set-output name=release_version::${RELEASE_VERSION}
          echo ::set-output name=snapshot_version::${SNAPSHOT_VERSION}

      - name: Release to github...
        id: github_release
        if: ${{ steps.verify.outputs.is_release_candidate  == 'true' &&  github.ref == 'refs/heads/master' }}
        run: |
          RELEASE_VERSION=${{ steps.prepare_release.outputs.release_version }}
          docker run --rm -v $PWD:/usr/src/mymaven -v ~/.m2:/root/.m2 -w /usr/src/mymaven maven:3.6.3-jdk-13 mvn versions:set -DnewVersion=$RELEASE_VERSION
          docker run --rm -v $PWD:/usr/src/mymaven -v ~/.m2:/root/.m2 -w /usr/src/mymaven maven:3.6.3-jdk-13 mvn install -B -e

          echo "Releasing JAR $RELEASE_VERSION to github packages..."
          curl -X PUT "https://maven.pkg.github.com/navikt/bidrag-tilgangskontroll/no/nav/bidrag/bidrag-tilgangskontroll/$RELEASE_VERSION/bidrag-tilgangskontroll-$RELEASE_VERSION.jar" \
          -H "Authorization: token ${GITHUB_TOKEN}" --upload-file "target/bidrag-tilgangskontroll-$RELEASE_VERSION.jar" -vvv
          curl -X PUT "https://maven.pkg.github.com/navikt/bidrag-tilgangskontroll/no/nav/bidrag/bidrag-tilgangskontroll/$RELEASE_VERSION/bidrag-tilgangskontroll-$RELEASE_VERSION.pom" \
          -H "Authorization: token ${GITHUB_TOKEN}" --upload-file "pom.xml" -vvv

          echo "Tagging HEAD_COMMIT with $RELEASE_VERSION.."
          git init
          git remote add origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git pull origin master
          git tag -a "$RELEASE_VERSION" -m "Release version $RELEASE_VERSION"
          git push origin "$RELEASE_VERSION"

      - name: Bump snapshot-version and commit ...
        id: bump_snapshot
        if: ${{ steps.verify.outputs.is_release_candidate == 'true' && github.ref == 'refs/heads/master' }}
        run: |
          SNAPSHOT_VERSION=${{ steps.prepare_release.outputs.snapshot_version }}
          git init
          git remote add origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git pull origin master
          docker run --rm -v $PWD:/usr/src/mymaven -v ~/.m2:/root/.m2 -w /usr/src/mymaven maven:3.6.3-jdk-13 mvn versions:set -DnewVersion=$SNAPSHOT_VERSION
          docker run --rm -v $PWD:/usr/src/mymaven -v ~/.m2:/root/.m2 -w /usr/src/mymaven maven:3.6.3-jdk-13 mvn -B -e release:update-versions
          NEW_SNAPSHOT_VERSION_LINE=$(grep version pom.xml | grep SNAPSHOT)
          NEW_SNAPSHOT_VERSION=$(echo "$NEW_SNAPSHOT_VERSION_LINE" | sed 's/version//g' | sed 's/  //' | sed 's;[</>];;g' | xargs)
          git add pom.xml
          git commit -m "Bumped to new snapshot version $NEW_SNAPSHOT_VERSION"
          git push --set-upstream origin master

