name: Build and release
on:
  push:
    branches:
      - '**'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  build:
    name: bidrag-tilgangskontroll, build and release...
    runs-on: self-hosted

    steps:
      - run: env
      - run: sudo rm -rf *
      - uses: actions/checkout@v2
      - uses: navikt/bidrag-maven/verify-dependencies@v1
        with:
          maven_image: maven:3.6.3-jdk-13
      - name: run maven batch install...
        run: docker run --rm -v $PWD:/usr/src/mymaven -v ~/.m2:/root/.m2 -w /usr/src/mymaven maven:3.6.3-jdk-13 mvn install -B -e

  release:
    name: release artifact to Maven repo
    needs: build
    runs-on: self-hosted

    steps:
      - run: env

      - uses: navikt/bidrag-release/verify-auto-release@v3
        id: verify
        if: github.ref == 'refs/heads/master-test'
        with:
          changelog_file: endringer.logg
          release_version: ${{ steps.prepare_release.outputs.release_version }}

      - name: Collect versions...
        id: prepare_release
        if: ${{ steps.verify.outputs.is_release_candidate  == 'true' &&  github.ref == 'refs/heads/master-test' }}
        run: |
          SNAPSHOT_VERSION_LINE=$(grep version pom.xml | grep SNAPSHOT)
          SNAPSHOT_VERSION=$(echo "$SNAPSHOT_VERSION_LINE" | sed 's/version//g' | sed 's/  //' | sed 's;[</>];;g' | xargs)
          RELEASE_VERSION=$(echo "$SNAPSHOT_VERSION" | sed 's/version//g' | sed 's/  //' | sed 's/-SNAPSHOT//' | sed 's;[</>];;g' | xargs)
          echo ::set-output name=release_version::${RELEASE_VERSION}
          echo ::set-output name=snapshot_version::${SNAPSHOT_VERSION}

      - name: Release to github...
        id: github_release
        if: ${{ steps.verify.outputs.is_release_candidate  == 'true' &&  github.ref == 'refs/heads/master-test' }}
        run: |
          RELEASE_VERSION=${{ steps.prepare_release.outputs.release_version }}
          docker run --rm -v $PWD:/usr/src/mymaven -v ~/.m2:/root/.m2 -w /usr/src/mymaven maven:3.6.3-jdk-13 mvn versions:set -DnewVersion=$RELEASE_VERSION
          docker run --rm -v $PWD:/usr/src/mymaven -v ~/.m2:/root/.m2 -w /usr/src/mymaven maven:3.6.3-jdk-13 mvn install -B -e
          curl -X PUT "https://maven.pkg.github.com/navikt/bidrag-tilgangskontroll/no/nav/bidrag/bidrag-tilgangskontroll/$RELEASE_VERSION/bidrag-tilgangskontroll-$RELEASE_VERSION.jar" \
          -H "Authorization: token ${GITHUB_TOKEN}" --upload-file "target/bidrag-tilgangskontroll-$RELEASE_VERSION.jar" -vvv
          curl -X PUT "https://maven.pkg.github.com/navikt/bidrag-tilgangskontroll/no/nav/bidrag/bidrag-tilgangskontroll/$RELEASE_VERSION/bidrag-tilgangskontroll-$RELEASE_VERSION.pom" \
          -H "Authorization: token ${GITHUB_TOKEN}" --upload-file "pom.xml" -vvv

      - name: Bump snapshot-version...
        id: bump_snapshot
        if: ${{ steps.verify.outputs.is_release_candidate == 'true' && github.ref == 'refs/heads/master-test' }}
        run : |
          SNAPSHOT_VERSION=${{ steps.prepare_release.outputs.snapshot_version }}
          docker run --rm -v $PWD:/usr/src/mymaven -v ~/.m2:/root/.m2 -w /usr/src/mymaven maven:3.6.3-jdk-13 mvn versions:set -DnewVersion=$SNAPSHOT_VERSION
          docker run --rm -v $PWD:/usr/src/mymaven -v ~/.m2:/root/.m2 -w /usr/src/mymaven maven:3.6.3-jdk-13 mvn -B -e release:update-versions
          NEW_SNAPSHOT_VERSION_LINE=$(grep version pom.xml | grep SNAPSHOT)
          NEW_SNAPSHOT_VERSION=$(echo "$NEW_SNAPSHOT_VERSION_LINE" | sed 's/version//g' | sed 's/  //' | sed 's;[</>];;g' | xargs)
          echo ::set-output name=new_snapshot_version::"$NEW_SNAPSHOT_VERSION"

      - name: Commit bumped snapshot-version...
        if: ${{ steps.verify.outputs.is_release_candidate == 'true' && github.ref == 'refs/heads/master-test' }}
        uses: navikt/bidrag-release/tag-n-commit-release@feature-docker-test
        with:
          commit_message: Bumped to new SNAPSHOT version after release of version ${{ steps.prepare.outputs.release_version }}
          tag_message: Released new version - ${{ steps.prepare.outputs.release_version }}
          pattern: pom.xml
          is_release_candidate: ${{ steps.verify.outputs.is_release_candidate }}
          release_version: ${{ steps.github_release.outputs.tag }}
          new_snapshot_version: ${{ steps.bump_snapshot.outputs.new_snapshot_version }}
          maven_image: maven:3.6.3-jdk-13
