name: maven deploy
on:
  push:
    branches:
      - '**'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: '15'
      - uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: navikt/bidrag-maven/setup@v4
        with:
          repositories: maven-central=https://repo.maven.apache.org/maven2,github-packages=https://maven.pkg.github.com/navikt/maven-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: navikt/bidrag-maven/verify-dependencies@v1
      - run: mvn -B install -e
      - uses: navikt/bidrag-release/prepare-mvn-pkg@v3
        id: prepare
        if: github.ref == 'refs/heads/feature/fix.tag-n-commit'
      - uses: navikt/bidrag-release/mvn-github-pkg@v3
        if: github.ref == 'refs/heads/feature/fix.tag-n-commit'
        with:
          new_snapshot_version: ${{ steps.prepare.outputs.new_snapshot_version }}
          release_version: ${{ steps.prepare.outputs.release_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: navikt/bidrag-release/tag-n-commit-release@feature/default
        if: github.ref == 'refs/heads/feature/fix.tag-n-commit'
        with:
          commit_message: Bumped to new SNAPSHOT version after release of version ${{ steps.prepare.outputs.release_version }}
          tag_message: Released new version - ${{ steps.prepare.outputs.release_version }}
          pattern: pom.xml
          tag: ${{ steps.prepare.outputs.release_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
