name: Build and release
on:
  push:
    branches:
      - '**'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  build:
    name: bidrag-tilgangskontroll, build and release...
    runs-on: self-hosted

    steps:
      - run: env
      - run: sudo rm -rf *
      - uses: actions/checkout@v2
      - uses: navikt/bidrag-maven/verify-dependencies@v1
        with:
          maven_image: maven:3.6.3-jdk-13
      - run: env
      - name: run maven batch install...
        run: docker run --rm -v $PWD:/usr/src/mymaven -v ~/.m2:/root/.m2 -w /usr/src/mymaven maven:3.6.3-jdk-13 mvn install -B -e

  release:
    name: release artifact to Maven repo
    needs: build
    runs-on: self-hosted

    steps:
      - run: |
          SNAPSHOT_VERSION=$(grep version pom.xml | grep SNAPSHOT)
          RELEASE_VERSION=$(echo "$SNAPSHOT_VERSION" | sed 's/version//g' | sed 's/  //' | sed 's/-SNAPSHOT//' | sed 's;[</>];;g' | xargs)
          run: docker run --rm -v $PWD:/usr/src/mymaven -v ~/.m2:/root/.m2 -w /usr/src/mymaven maven:3.6.3-jdk-13 mvn versions:set -DnewVersion=$RELEASE_VERSION
          echo "RELEASE_VERSION: $RELEASE_VERSION"
          echo "PWD: " $PWD
          curl -X PUT "https://maven.pkg.github.com/navikt/bidrag-tilgangskontroll/no/nav/bidrag.tilgangskontroll/$RELEASE_VERSION/bidrag-tilgangskontroll-1.2.jar" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" --upload-file "{full sti}/bidrag-tilgangskontroll-$RELEASE_VERSION.jar" -vvv
