name: Build and release
on:
  push:
    branches:
      - '**'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  build:
    name: bidrag-tilgangskontroll, build and release...
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: navikt/bidrag-maven/verify-dependencies@v1
        with:
          maven_image: maven:3.6.3-jdk-13
      - run: env
      - name: run maven batch install...
        run: docker run --rm -v $PWD:/usr/src/mymaven -v ~/.m2:/root/.m2 -w /usr/src/mymaven maven:3.6.3-jdk-13 mvn install -B -e

  release:
    name: release artifact to Maven repo
    needs: build
    runs-on: self-hosted

    steps:
      - uses: navikt/bidrag-release/prepare-mvn-pkg@v3
        id: prepare
        if: github.ref == 'refs/heads/never-run'

      - uses: navikt/bidrag-release/verify-auto-release@v3
        id: verify
        if: github.ref == 'refs/heads/never-run'
        with:
            changelog_file: README.md
            release_version: ${{ steps.prepare.outputs.release_version }}

      - uses: navikt/bidrag-release/tag-n-commit-release@v3
        if: github.ref != 'refs/heads/never-run'
        with:
          commit_message: Bumped to new SNAPSHOT version after release of version ${{ steps.prepare.outputs.release_version }}
          tag_message: Released new version - ${{ steps.prepare.outputs.release_version }}
          pattern: pom.xml
          is_release_candidate: ${{ steps.verify.outputs.is_release_candidate }}
          tag: ${{ steps.prepare.outputs.release_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
