name: Build and release
on:
  push:
    branches:
      - '**'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MAVEN_IMAGE: maven:3.6.3-jdk-13

jobs:

  build:
    name: bidrag-tilgangskontroll, build and release...
    runs-on: self-hosted

    steps:
      - run: env
      - run: sudo rm -rf *
      - uses: actions/checkout@v2
      - uses: navikt/bidrag-maven/verify-dependencies@v1
        with:
          maven_image: $MAVEN_IMAGE
      - run: env
      - name: run maven batch install...
        run: docker run --rm -v $PWD:/usr/src/mymaven -v ~/.m2:/root/.m2 -w /usr/src/mymaven $MAVEN_IMAGE mvn install -B -e

  release:
    name: release artifact to Maven repo
    needs: build
    runs-on: self-hosted

    steps:
      - run: env

      - run: |
          SNAPSHOT_VERSION=$(grep version pom.xml | grep SNAPSHOT)
          RELEASE_VERSION=$(echo "$SNAPSHOT_VERSION" | sed 's/version//g' | sed 's/  //' | sed 's/-SNAPSHOT//' | sed 's;[</>];;g' | xargs)
          echo ::set-output name=tag::${RELEASE_VERSION}
        id: prepare_release

      - uses: navikt/bidrag-release/verify-auto-release@v3
        id: verify
        if: github.ref != 'refs/heads/master'
        with:
          changelog_file: endringer.logg
          release_version:  ${{ steps.prepare_release.outputs.tag }}

      - name: Release to github...
        if: ${{ steps.verify.outputs.is_release_candidate }} == 'true' &&  github.ref == 'refs/heads/master'
        id: github_release
        run: |
          RELEASE_VERSION=${{ steps.release.outputs.tag }}
          docker run --rm -v $PWD:/usr/src/mymaven -v ~/.m2:/root/.m2 -w /usr/src/mymaven $MAVEN_IMAGE mvn versions:set -DnewVersion=$RELEASE_VERSION
          docker run --rm -v $PWD:/usr/src/mymaven -v ~/.m2:/root/.m2 -w /usr/src/mymaven $MAVEN_IMAGE mvn install -B -e
          curl -X PUT "https://maven.pkg.github.com/navikt/bidrag-tilgangskontroll/no/nav/bidrag/bidrag-tilgangskontroll/$RELEASE_VERSION/bidrag-tilgangskontroll-$RELEASE_VERSION.jar" \
          -H "Authorization: token ${GITHUB_TOKEN}" --upload-file "target/bidrag-tilgangskontroll-$RELEASE_VERSION.jar" -vvv
          curl -X PUT "https://maven.pkg.github.com/navikt/bidrag-tilgangskontroll/no/nav/bidrag/bidrag-tilgangskontroll/$RELEASE_VERSION/bidrag-tilgangskontroll-$RELEASE_VERSION.pom" \
          -H "Authorization: token ${GITHUB_TOKEN}" --upload-file "pom.xml" -vvv
          docker run --rm -v $PWD:/usr/src/mymaven -v ~/.m2:/root/.m2 -w /usr/src/mymaven $MAVEN_IMAGE -B -e release:update-versions
          NEW_SNAPSHOT_VERSION=$(grep version pom.xml | grep SNAPSHOT)
          echo ::set-output name=new_snapshot_version::"$NEW_SNAPSHOT_VERSION"

      - name: Bump snapshot-version...
        if: ${{ steps.verify.outputs.is_release_candidate }} == 'true' &&  github.ref == 'refs/heads/master'
        uses: navikt/bidrag-release/tag-n-commit-release@feature-docker
        with:
          commit_message: Bumped to new SNAPSHOT version after release of version ${{ steps.prepare.outputs.release_version }}
          tag_message: Released new version - ${{ steps.prepare.outputs.release_version }}
          pattern: pom.xml
          is_release_candidate: ${{ steps.verify.outputs.is_release_candidate }}
          release_version: ${{ steps.github_release.outputs.tag }}
          new_snapshot_version: ${{ steps.github_release.outputs.new_snapshot_version }}
          maven_image: $MAVEN_IMAGE



